### ISSUE TITLE
Application crash when trying to display a "long" post

### ISSUE THREAD

**Issue by StefOfficiel** [Flaburgan/diaspora-webapp#17]
Bien le bonjour,

En faite, l'appli crash carrément dès qu'une discussion est longue. Par ex, dès que je tente d’accéder à la fameuse discussion qui fait tant débat, elle s'ouvre se charge et dès que les messages sont en train de charger, l'application ferme aussitôt. Aucun problème sur Mozilla ou Chrome. Je suis sur un S3 - Android PACman.

**Comment by Flaburgan** [comment]
No answer for more than a year, closing.
